# CONDITIONAL OPERATOR --> A ONE-LINE SHORTCUT FOR THE if-else STATEMENT (TERNARY OPERATOR) ..... PRINT OR ASSIGN ONE OF TWO VALUES BASED ON A CONDITION X IF CONDITON ELSE Y

num = -5

print("positive" if num>0 else "negative")